name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      -
        name: Upload artifact dms_linux_arm64
        uses: actions/upload-artifact@v2
        with:
          name: dms_linux_arm64
          path: dist/dms_linux_arm64/dms
      -
        name: Upload artifact dms_linux_amd64
        uses: actions/upload-artifact@v2
        with:
          name: dms_linux_amd64
          path: dist/dms_linux_amd64/dms
      -
        name: Upload artifact dms_linux_386
        uses: actions/upload-artifact@v2
        with:
          name: dms_linux_386
          path: dist/dms_linux_386/dms
      -
        name: Upload artifact dms_linux_arm
        uses: actions/upload-artifact@v2
        with:
          name: dms_linux_arm
          path: dist/dms_linux_arm/dms
      -
        name: Upload artifact dms_darwin_arm64
        uses: actions/upload-artifact@v2
        with:
          name: dms_darwin_arm64
          path: dist/dms_darwin_arm64/dms
      -
        name: Upload artifact dms_darwin_amd64
        uses: actions/upload-artifact@v2
        with:
          name: dms_darwin_amd64
          path: dist/dms_darwin_amd64/dms
      -
        name: Upload artifact dms_darwin_386
        uses: actions/upload-artifact@v2
        with:
          name: dms_darwin_386
          path: dist/dms_darwin_386/dms
      -
        name: Upload artifact dms_darwin_arm
        uses: actions/upload-artifact@v2
        with:
          name: dms_darwin_arm
          path: dist/dms_darwin_arm/dms
